Request for code review
Phys767-Spring17/Particle-Simulator pull request #1
Opened 2017-04-19 05:49 UTC by anisak000

This repository has code based on that from the textbook chapter on Classes. I wrote a test for the Quarks code.

2017-04-19 13:19 UTC, ECGonzales reviewed
Remove.pyc and .cache files from git

2017-04-19 13:19 UTC, ECGonzales commented on Particles.py
> +print(higgs.roar)
Add blank line to end of file

2017-04-19 14:00 UTC, dcuffari requested changes

2017-04-19 14:00 UTC, dcuffari commented on Instances.py
> +obs.append(p.Particle())
running this code fails due to the missing argument in Particle(). This method is currently defined in particle.py as requiring 4 arguments; self, charge, mass, position. So the line should look like, 

obs.append(p.Particle(1,1,1))

Making this change allowed for the code to run correctly.

2017-04-19 14:00 UTC, dcuffari commented on Instances.py
> +obs.append(p.Particle())
This also requires 4 arguments (counting self).

2017-04-19 14:00 UTC, dcuffari commented on Quarks/test_quark.py
> +    assert t.flip("up") == "down"
flip only takes one argument (self).

2017-04-19 14:00 UTC, dcuffari commented on Quarks/test_quark.py
> +    assert t.flip("up") == "down"
A way that works is the following,

t.flavor = "up"
t.flip()
assert t.flavor == "down"

This passes and tests the method.

2017-04-26 02:55 UTC, anisak000 commented
I have implemented all required changes. The tests work too. Thanks for the generous code review!

2017-04-26 02:55 UTC, merged